import './mixin-CanvasRenderer';
import './mixin-WebGLRenderer';
import './mixin-TransformStatic';
import './mixin-Transform';
import './mixin-DisplayObject';
import './mixin-Container';
import './mixin-Sprite';
import './mixin-AnimatedSprite';
import './mixin-Text';
